from enum import Enum


class ParticipantRole(Enum):
    buyer = "buyer"
    seller = "seller"
    tenant = "tenant"
    landlord = "landlord"
    buyer_agent = "buyer_agent"
    seller_agent = "seller_agent"
    dual_agent = "dual_agent"
    buyer_attorney = "buyer_attorney"
    seller_attorney = "seller_attorney"
    dual_attorney = "dual_attorney"
    buyer_broker = "buyer_broker"
    seller_broker = "seller_broker"
    dual_broker = "dual_broker"
    lender = "lender"
    contractor = "contractor"
    inspector = "inspector"
    appraiser = "appraiser"
    title_officer = "title_officer"
    property_manager = "property_manager"
    custom = "custom"
    unknown = "unknown"
